# Generated by Django 3.1.4 on 2021-01-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='Role',
            new_name='role',
        ),
    ]
