# Generated by Django 3.1.5 on 2021-01-07 16:22

import ckeditor.fields
import datetime
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='media/ytubers/%Y/%m/')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('subject', models.CharField(choices=[('English Language Arts', 'English Language Arts'), ('Art / Music / Theater', 'Art / Music / Theater'), ('Social Sciences', 'Social Sciences'), ('Mathematics', 'Mathematics'), ('Science', 'Science'), ('World Language', 'World Language'), ('Professional Career', 'Professional Career'), ('Multiple Subjects', 'Multiple Subjects'), ('Other', 'Other')], max_length=255)),
                ('video_url', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('city', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('rate', models.FloatField(default=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
