# Generated by Django 3.1.5 on 2021-01-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20210109_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teaching_experience',
            field=models.IntegerField(default=1),
        ),
    ]
