# Generated by Django 3.1.5 on 2021-01-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20210109_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='salary_annual',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='salary_monthly',
            new_name='qualification',
        ),
        migrations.AddField(
            model_name='teacher',
            name='area_of_interest',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='teacher',
            name='awards',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AddField(
            model_name='teacher',
            name='books_published',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='teacher',
            name='designation',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaching_experience',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
